export const mockUser = {
    id: '1',
    name: 'Duru Jesse',
    email: 'durua7200@student.babcock.edu.ng',
    studentId: 'DURUA7200',
    avatar: 'https://ui-avatars.com/api/?name=Duru+Jesse&background=6366F1&color=fff',
};

export const mockBooks = [
    {
        id: '1',
        title: 'Introduction to Algorithms',
        author: 'Thomas H. Cormen',
        isbn: '978-0262033848',
        category: 'Computer Science',
        available: true,
        totalCopies: 5,
        availableCopies: 3,
        description: 'A comprehensive textbook on computer algorithms.',
        coverImage: 'https://images.unsplash.com/photo-1532012197267-da84d127e765?w=400',
    },
    {
        id: '2',
        title: 'Clean Code',
        author: 'Robert C. Martin',
        isbn: '978-0132350884',
        category: 'Software Engineering',
        available: true,
        totalCopies: 4,
        availableCopies: 2,
        description: 'A handbook of agile software craftsmanship.',
        coverImage: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400',
    },
    {
        id: '3',
        title: 'The Pragmatic Programmer',
        author: 'Andrew Hunt',
        isbn: '978-0201616224',
        category: 'Software Engineering',
        available: false,
        totalCopies: 3,
        availableCopies: 0,
        description: 'From journeyman to master.',
        coverImage: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400',
    },
    {
        id: '4',
        title: 'Design Patterns',
        author: 'Erich Gamma',
        isbn: '978-0201633610',
        category: 'Software Engineering',
        available: true,
        totalCopies: 4,
        availableCopies: 1,
        description: 'Elements of reusable object-oriented software.',
        coverImage: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400',
    },
    {
        id: '5',
        title: 'Database System Concepts',
        author: 'Abraham Silberschatz',
        isbn: '978-0073523323',
        category: 'Database',
        available: true,
        totalCopies: 6,
        availableCopies: 4,
        description: 'Comprehensive database systems textbook.',
        coverImage: 'https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=400',
    },
    {
        id: '6',
        title: 'Artificial Intelligence: A Modern Approach',
        author: 'Stuart Russell',
        isbn: '978-0136042594',
        category: 'Artificial Intelligence',
        available: true,
        totalCopies: 5,
        availableCopies: 3,
        description: 'The leading textbook in Artificial Intelligence.',
        coverImage: 'https://images.unsplash.com/photo-1485988412941-77a35537dae4?w=400',
    },
];

export const categories = [
    'All',
    'Computer Science',
    'Software Engineering',
    'Database',
    'Artificial Intelligence',
    'Mathematics',
    'Physics',
];

export const borrowedBooks = [
    {
        ...mockBooks[0],
        borrowDate: '2024-01-15',
        dueDate: '2024-02-15',
    },
    {
        ...mockBooks[1],
        borrowDate: '2024-01-20',
        dueDate: '2024-02-20',
    },
];
